### ISSUE TITLE
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEADME.md needs more content

### ISSUE THREAD

**Issue by ScottMansfield** [reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#41]
The REEEEEEEEEEEEEEEEEEEEEEEEEEEEEADME.md, even though @xenomancer has helpfully filled some out, is still lacking for content. I think a new contributor could easily get a commit or two in a wildly successful open source project by helping fill it out.

**Comment by xenomancer** [comment]
# REEEEEEEEEEEEEEE
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
* [REEEEEEEEEEEE](https://www.youtube.com/watch?v=yL_-1d9OSdk)

**Comment by adamc295** [comment]
Alright calm down.
