### ISSUE TITLE
reee.zip

### ISSUE THREAD

**Issue by shreyasminocha** [reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#68]
Someone could use [this idea](https://alf.nu/ZipQuine) and create a `reee.zip` containing `r` and `e.zip` (containing `e` and `e.zip` (containing `e` and `e.zip`) and so on). Unfortunately, I don't have the skills to do this.

**Comment by ScottMansfield** [comment]
what a fantastic fucking idea

**Comment by Wetwer** [comment]
zip bomb
