### ISSUE TITLE
reee.gif

### ISSUE THREAD

**Issue by shreyasminocha** [reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee#69]
A seamless looping animated gif that begins with `r` and goes `eeeeeee...`?

**Comment by xenomancer** [comment]
Some "betas" for you.

![ezgif-1-4e496f954f20](https://user-images.githubusercontent.com/1974682/50533117-7eaa5900-0af1-11e9-9153-05bb3bc2ebcd.gif)


![ezgif-1-de3d4bf544a0](https://user-images.githubusercontent.com/1974682/50533166-0c864400-0af2-11e9-8810-0c3e4643c48f.gif)


![ezgif-1-2ff6d66fb73d](https://user-images.githubusercontent.com/1974682/50533226-6d624c00-0af3-11e9-9fe4-1e82919ca6c9.gif)

**Comment by shreyasminocha** [comment]
@xenomancer We could have a single, static "R" in the upper half of the gif and either flashing "E"s like in your demo or smaller, scrolling "E"s in the lower half.

**Comment by ScottMansfield** [comment]
closed in #85
